M48
; DRILL file {KiCad 7.0.9} date Mon May  6 20:13:29 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-06T20:13:29+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1260
%
G90
G05
T2
X6.315Y-3.3366
T3
X7.7976Y-4.4421
T4
X7.7976Y-5.2295
T5
X3.9764Y-2.4252
X3.9764Y-5.5118
X7.8531Y-5.5118
X7.8622Y-2.4252
T1
G00X6.315Y-3.6236
M15
G01X6.315Y-3.6402
M16
G05
T0
M30
